export const carFeatureCategories = [
    {
      category: 'Safety',
      features: [
        'Anti-Lock Braking System (ABS)',
        'Lane Keep Assist System (LKAS)',
        'Electronic Brake-Force Distribution (EBD)',
        'Lane Departure Warning System (LDWS)',
        'Brake Assist (BA)',
        'BlindSpot Detection (BSD)',
        'Traction Control',
        'Rear Cross Traffic Alert (RCTA)',
        'Vehicle Stability Control',
        'Rear Cross Traffic Brake (RCTB)',
        'Rollover Stability Control (RSC)',
        'Moving Object Detection System',
        'Hill Start Assist Control',
        'Surround View Monitor (SVM)',
        'Down Hill Assist Control',
        'Parking Distance Warning (PDW)',
        'Runflat Tyres',
        'Night Vision',
        'Speed Limiter',
        'Door Opening Warning',
        'Speed Sensing Auto Door Lock',
        'Crash Auto Door Unlock',
        'Child Lock',
        'Active Bonet',
        'ISOFIX Child Seat Anchors',
        'Active Headrest',
        'No. of Seatbelts',
        'Active Steering',
        'Driver Seat Belt Warning',
        'Driver Attention Warning (DAW)',
        'Passenger Seat Belt Warning',
        'Anti-Theft Alarm System',
        'No. of Airbags',
        'Anti Theft Wheel Bolts',
        'Advanced Air Bags System (AABS)',
        'Immobilizer',
        'Autonomous Emergency Braking (AEB)',
        'Handbrake Manual',
        'Collision Detection',
        'ANCAP Safety Rating',
        'NCAP Safety Rating',
        '540° Camera',
      ],
    },
    {
      category: 'Exterior',
      features: [
        'Alloy Wheels',
        'Rear Wiper',
        'Adjustable Headlights',
        'Rear Spoiler',
        'LED Headlights',
        'Roof Rails',
        'Fog Lights',
        'Side Steps',
        'Rear Fog Lamp',
        'Dual Exhaust',
        'DRLs',
        'Power Boot',
        'High Mount Stop Lamp',
        'Colored Outside Door Handles',
        'Body Colored Defogger',
        'Wind Blocker',
        'Side Mirrors with Indicators',
        'Rain Sensing Wipers',
        'Auto Retractable Side Mirrors',
        'Heated Side Mirrors',
        'Panaromic Sun-Roof',
        'Sun Roof',
        'Moon Roof',
      ],
    },
    {
      category: 'Infotainment and Instrumentation',
      features: [
        'AM/FM Radio',
        'Android Auto',
        'Cassette Player',
        'Apple Car Play',
        'CD Player',
        'Navigation',
        'DVD Player',
        'Optional Navigation',
        'Front Speakers',
        'Rear Seat Entertainment',
        'Rear Speakers',
        'Voice Control',
        'Number of Speakers 2',
        'Display Size 7.0 in',
        'Standard LCD',
        'USB and Auxillary Cable',
        'Instrument Cluster Analogue with MID',
        'Bluetooth Connectivity',
        'Tachometer',
        'Multi Info',
        'Heads Up Display (HUD)',
        'Wireless CarPlay',
      ],
    },
    {
      category: 'Comfort and Convenience',
      features: [
        'Air Conditioner',
        'Seat Material Type Fabric',
        'Seats with Manual Adjustments',
        'Climate Control',
        'Driver Seat Electric Adjustment',
        'Heater',
        'Passenger Seat Electric Adjustment',
        'Heated Seats',
        'Driver Seat Lumbar Support',
        'Ventilated Seats',
        'Driver Seat Memory Function',
        'Rear AC Vents',
        'Boss Seat Switch',
        '3rd Row AC Vents',
        'Air Purifier',
        'Power Steering',
        'CoolBox',
        'Power Windows',
        'Cup Holders',
        'Power Door Locks',
        'Arm Rest',
        'Power Mirrors',
        'Sun Visor',
        'Central Locking',
        'Vanity Mirror',
        'Keyless Entry',
        'Glove Box Lamp',
        'Key Type',
        'Keyless Entry',
        'Cargo Light',
        'Push Start',
        'Interior Lighting',
        'Remote Engine Start',
        'Ambient Light',
        'Remote Boot/Fuel-Lid',
        'Front Power Outlet',
        'Cruise Control',
        'Rear Power Outlet',
        'Smart Cruise Control',
        'Front Parking Sensors',
        'Driving Modes',
        'Rear Parking Sensors',
        'Auto Brake Hold',
        'Auto Parking System',
        'Paddle Shifter',
        'Auto-Dimming Rear View Mirror',
        'Steering Adjustment',
        'Automatic Head Lamps',
        'Steering Switches',
        'Headlight On Reminder',
        'Heated Steering',
        'Road Sign Assist',
        'Rear Folding Seat',
        'Gas Shock Absorber',
        'Rear Headrest',
        'Rear Central Control',
        '360 Camera',
        'Electric Curtain – Rear',
        'Front Camera',
        'Electric Curtain – Front',
        'Rear Camera',
        'Live Traffic Information',
      ],
    },
  ];