export const languages = {
    en: {
      label: 'English',
      flag: '🇬🇧',
      wizard: {
        progress: 'Step {current} / {total}',
        complete: '{percent}% Complete',
        back: 'Back',
        next: 'Next',
        findCar: 'Chacha, Find My Car!',
        finding: 'Searching...',
        trust: 'Chacha Match™ Scoring System - 100% Transparent',
        steps: {
          budget: {
            title: "What's Your Budget?",
            subtitle: 'Select your price range',
            description: 'Tell Chacha how much you want to spend',
          },
          bodyType: {
            title: 'Which Body Type?',
            subtitle: 'Choose your preferred style',
            description: 'Sedan, SUV, or Hatchback - what do you like?',
          },
          familySize: {
            title: 'How Many People Travel?',
            subtitle: 'Based on family size',
            description: 'Chacha will find the best car for your family',
          },
          driving: {
            title: 'Where Do You Drive?',
            subtitle: 'City, Highway, or Both',
            description: 'Based on your driving habits',
          },
          fuel: {
            title: 'Fuel Preference?',
            subtitle: 'Petrol, Hybrid, or Electric',
            description: 'How important is fuel economy to you?',
          },
          transmission: {
            title: 'Gear Preference?',
            subtitle: 'Manual or Automatic',
            description: 'Which transmission do you prefer?',
          },
          priorities: {
            title: "What's Most Important?",
            subtitle: 'Select your priorities',
            description: 'Chacha will use these in scoring',
          },
        },
        options: {
          budget: [
            { label: 'Under 20 Lakh', tag: 'Budget Pick' },
            { label: '20-30 Lakh', tag: 'Popular' },
            { label: '30-40 Lakh', tag: 'Mid Range' },
            { label: '40-50 Lakh', tag: 'Premium' },
            { label: '50-70 Lakh', tag: 'Executive' },
            { label: '70 Lakh+', tag: 'Luxury' },
          ],
          bodyType: [
            { label: 'Hatchback', desc: 'Compact & Efficient' },
            { label: 'Sedan', desc: 'Classic & Comfortable' },
            { label: 'SUV', desc: 'Spacious & Powerful' },
            { label: 'Crossover', desc: 'Versatile & Modern' },
            { label: 'MPV', desc: 'Family Oriented' },
            { label: 'No Preference', desc: 'Show All' },
          ],
          familySize: [
            { label: '1-2 People', desc: 'Solo or Couple' },
            { label: '3-4 People', desc: 'Small Family' },
            { label: '5+ People', desc: 'Full Family' },
            { label: 'Large Family', desc: 'Need Max Space' },
          ],
          driving: [
            { label: 'Mostly City', desc: 'Daily Commute' },
            { label: 'Mostly Highway', desc: 'Long Drives' },
            { label: 'Mixed', desc: 'Both Equal' },
          ],
          fuel: [
            { label: 'Petrol', desc: 'Classic Choice' },
            { label: 'Hybrid', desc: 'Fuel Saver' },
            { label: 'Electric', desc: 'Future Ready' },
            { label: 'No Preference', desc: 'Any Fuel' },
          ],
          transmission: [
            { label: 'Manual', desc: 'Full Control' },
            { label: 'Automatic', desc: 'Easy Drive' },
            { label: 'No Preference', desc: 'Either Works' },
          ],
          priorities: [
            { label: 'Fuel Economy', value: 'fuel-economy' },
            { label: 'Safety', value: 'safety' },
            { label: 'Features', value: 'features' },
            { label: 'Comfort', value: 'comfort' },
            { label: 'Performance', value: 'performance' },
            { label: 'Resale Value', value: 'resale' },
            { label: 'Low Maintenance', value: 'maintenance' },
            { label: 'Family Friendly', value: 'family' },
            { label: 'Value for Money', value: 'value' },
          ],
        },
      },
    },
    ur: {
      label: 'اردو',
      flag: '🇵🇰',
      wizard: {
        progress: 'مرحلہ {current} / {total}',
        complete: '{percent}% مکمل',
        back: 'پیچھے',
        next: 'آگے بڑھیں',
        findCar: 'چاچا، گاڑی ڈھونڈو!',
        finding: 'ڈھونڈ رہا ہے...',
        trust: 'چاچا میچ™ سکورنگ سسٹم - 100% شفاف',
        steps: {
          budget: {
            title: 'آپ کا بجٹ کیا ہے؟',
            subtitle: 'اپنی قیمت کی حد منتخب کریں',
            description: 'چاچا کو بتائیں کتنا خرچ کرنا چاہتے ہیں',
          },
          bodyType: {
            title: 'کونسی باڈی ٹائپ؟',
            subtitle: 'اپنی پسند منتخب کریں',
            description: 'سیڈان، ایس یو وی، یا ہیچ بیک',
          },
          familySize: {
            title: 'کتنے لوگ سفر کریں گے؟',
            subtitle: 'فیملی کے لحاظ سے',
            description: 'چاچا فیملی کے لیے بہترین گاڑی ڈھونڈے گا',
          },
          driving: {
            title: 'آپ کہاں چلاتے ہیں؟',
            subtitle: 'شہر، ہائی وے، یا دونوں',
            description: 'آپ کی ڈرائیونگ عادات کے مطابق',
          },
          fuel: {
            title: 'فیول کیا پسند ہے؟',
            subtitle: 'پیٹرول، ہائبرڈ، یا الیکٹرک',
            description: 'فیول اکانومی کتنی اہم ہے؟',
          },
          transmission: {
            title: 'گیئر کیسا؟',
            subtitle: 'مینوئل یا آٹومیٹک',
            description: 'آپ کو کونسی ٹرانسمیشن چاہیے؟',
          },
          priorities: {
            title: 'سب سے اہم کیا ہے؟',
            subtitle: 'اپنی ترجیحات منتخب کریں',
            description: 'چاچا ان ترجیحات کو اسکورنگ میں رکھے گا',
          },
        },
        options: {
          budget: [
            { label: '20 لاکھ سے کم', tag: 'بجٹ' },
            { label: '20-30 لاکھ', tag: 'مقبول' },
            { label: '30-40 لاکھ', tag: 'درمیانہ' },
            { label: '40-50 لاکھ', tag: 'پریمیم' },
            { label: '50-70 لاکھ', tag: 'ایگزیکٹو' },
            { label: '70 لاکھ+', tag: 'لگژری' },
          ],
          bodyType: [
            { label: 'ہیچ بیک', desc: 'کمپیکٹ اور موثر' },
            { label: 'سیڈان', desc: 'کلاسک اور آرام دہ' },
            { label: 'ایس یو وی', desc: 'کشادہ اور طاقتور' },
            { label: 'کراس اوور', desc: 'ورسٹائل اور جدید' },
            { label: 'ایم پی وی', desc: 'فیملی کے لیے' },
            { label: 'کوئی بھی', desc: 'سب دیکھیں' },
          ],
          familySize: [
            { label: '1-2 لوگ', desc: 'اکیلے یا جوڑا' },
            { label: '3-4 لوگ', desc: 'چھوٹا فیملی' },
            { label: '5+ لوگ', desc: 'پورا فیملی' },
            { label: 'بڑا فیملی', desc: 'زیادہ جگہ چاہیے' },
          ],
          driving: [
            { label: 'زیادہ شہر', desc: 'روزانہ آمدورفت' },
            { label: 'زیادہ ہائی وے', desc: 'لمبے سفر' },
            { label: 'دونوں برابر', desc: 'مکسڈ ڈرائیونگ' },
          ],
          fuel: [
            { label: 'پیٹرول', desc: 'کلاسک انتخاب' },
            { label: 'ہائبرڈ', desc: 'فیول سیور' },
            { label: 'الیکٹرک', desc: 'مستقبل کے لیے' },
            { label: 'کوئی بھی', desc: 'کوئی بھی فیول' },
          ],
          transmission: [
            { label: 'مینوئل', desc: 'مکمل کنٹرول' },
            { label: 'آٹومیٹک', desc: 'آسان ڈرائیونگ' },
            { label: 'کوئی بھی', desc: 'دونوں چلے گا' },
          ],
          priorities: [
            { label: 'فیول اکانومی', value: 'fuel-economy' },
            { label: 'سیفٹی', value: 'safety' },
            { label: 'فیچرز', value: 'features' },
            { label: 'آرام', value: 'comfort' },
            { label: 'پرفارمنس', value: 'performance' },
            { label: 'ری سیل ویلیو', value: 'resale' },
            { label: 'کم مینٹیننس', value: 'maintenance' },
            { label: 'فیملی فرینڈلی', value: 'family' },
            { label: 'پیسے کی قیمت', value: 'value' },
          ],
        },
      },
    },
    ar: {
      label: 'العربية',
      flag: '🇸🇦',
      wizard: {
        progress: 'الخطوة {current} / {total}',
        complete: '{percent}% اكتمل',
        back: 'رجوع',
        next: 'التالي',
        findCar: 'تشاتشا، جد لي سيارة!',
        finding: 'جارٍ البحث...',
        trust: 'نظام تشاتشا ماتش™ - شفاف 100%',
        steps: {
          budget: {
            title: 'ما هي ميزانيتك؟',
            subtitle: 'اختر نطاق السعر',
            description: 'أخبر تشاتشا كم تريد أن تنفق',
          },
          bodyType: {
            title: 'ما نوع الهيكل؟',
            subtitle: 'اختر النمط المفضل',
            description: 'سيدان، SUV، أو هاتشباك',
          },
          familySize: {
            title: 'كم عدد المسافرين؟',
            subtitle: 'حسب حجم العائلة',
            description: 'سيجد تشاتشا أفضل سيارة لعائلتك',
          },
          driving: {
            title: 'أين تقود؟',
            subtitle: 'المدينة، الطريق السريع، أو كليهما',
            description: 'حسب عادات القيادة',
          },
          fuel: {
            title: 'نوع الوقود؟',
            subtitle: 'بنزين، هجين، أو كهربائي',
            description: 'ما أهمية الاقتصاد في الوقود؟',
          },
          transmission: {
            title: 'ناقل الحركة؟',
            subtitle: 'يدوي أو أوتوماتيك',
            description: 'أي ناقل حركة تفضل؟',
          },
          priorities: {
            title: 'ما الأهم؟',
            subtitle: 'اختر أولوياتك',
            description: 'سيستخدم تشاتشا هذه في التقييم',
          },
        },
      },
    },
  };